### ISSUE TITLE
Add unified format?

### ISSUE THREAD

**Issue by lauraerinmann** [amweiss/angular-diff-match-patch#25]
Is there a way to add this functionality to this library? [wiki](https://en.wikipedia.org/wiki/Diff_utility#Unified_format)  Haven't been able to come up with a way to add it to the wrapper, but the google API mentions this.

**Comment by amweiss** [comment]
Hm, that should be the `patch` portion of `diff-match-patch`. I should be able to do that one, I'll take a look this weekend.

**Comment by amweiss** [comment]
So https://code.google.com/p/google-diff-match-patch/wiki/Unidiff specifically mentions the `patch` format resembles the unidiff format, but is different. I can add the patch functionality for displaying in html or download, but it would need to be read back in by an implementation of `google-diff-match-patch` rather than the GNU tools. Is that sufficient for what you are looking for, or do you want an actual unidiff output, because I won't be able to add that.
